import { GoogleGenerativeAI } from "@google/generative-ai";

async function generateWithRetry(model, prompt, retries = 3, delay = 2000) {
  for (let attempt = 1; attempt <= retries; attempt++) {
    try {
      const result = await model.generateContent(prompt);
      return result;
    } catch (error) {
      if (error.status === 503 && attempt < retries) {
        await new Promise((r) => setTimeout(r, delay));
      } else {
        throw error;
      }
    }
  }
}

const analyze = async (req,res)=>{
    try{
        const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
        const { code } = req.body;
        if(!code) return res.status(400).json({
            error: "No code provided",
        });
        const model =   genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
        const prompt = 
            `Analyze the following code and explain briefly.
            Return the exact structure:
            Time Complexity: <Big-O>
            Space Complexity: <Big-O>
            Why: <6-7 line explanation with only relevant points>
            Code: ${code}`;
        const payload = { contents: [{ role: "user",parts: [{ text: prompt }] }] };
        const result = await generateWithRetry(model, payload);
        const responseText = result.response.text() || "";
        return res.json({
            explanation: responseText || "No Content Generated by gemini",
        });
    }catch(error){
        console.log("Error:",error);
        return res.status(500).json({ error: "Internal Server error" });
    }
};

export default analyze;